-- Super Admin upgrade for the IFAR Portal
-- IMPORTANT: Replace the placeholder email below before running this script.

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = any (
    array[
      'admin@tsiwealth.com'
      
    ]::text[]
  );
$$;

revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to authenticated;

alter table public.claim_records
  add column if not exists received_at timestamptz,
  add column if not exists returned_at timestamptz,
  add column if not exists return_reason text,
  add column if not exists admin_action_by uuid references auth.users(id) on delete set null,
  add column if not exists admin_action_email text;

-- Expand any earlier status check so the admin workflow can use its new states.
do $$
declare constraint_name text;
begin
  for constraint_name in
    select conname
    from pg_constraint
    where conrelid = 'public.claim_records'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format('alter table public.claim_records drop constraint %I', constraint_name);
  end loop;
end $$;

alter table public.claim_records
  add constraint claim_records_status_check
  check (status in ('DRAFT', 'SUBMITTED', 'READY', 'SENT_TO_CLAIM_DEPT', 'RECEIVED', 'RETURNED'));

create table if not exists public.claim_admin_events (
  id bigint generated by default as identity primary key,
  claim_id uuid not null references public.claim_records(id) on delete cascade,
  adviser_id uuid references auth.users(id) on delete set null,
  admin_id uuid references auth.users(id) on delete set null,
  admin_email text,
  action text not null check (action in ('RECEIVED', 'RETURNED')),
  reason text,
  recipient_email text,
  provider_message_id text,
  occurred_at timestamptz not null default now()
);

create table if not exists public.confirmation_reminder_events (
  id bigint generated by default as identity primary key,
  confirmation_id uuid not null references public.confirmation_requests(id) on delete cascade,
  adviser_id uuid references auth.users(id) on delete set null,
  admin_id uuid references auth.users(id) on delete set null,
  admin_email text,
  recipient_type text not null check (recipient_type in ('CLIENT', 'IFAR')),
  recipient_email text not null,
  provider_message_id text,
  occurred_at timestamptz not null default now()
);

create index if not exists claim_admin_events_claim_idx
  on public.claim_admin_events(claim_id, occurred_at desc);
create index if not exists confirmation_reminder_events_confirmation_idx
  on public.confirmation_reminder_events(confirmation_id, occurred_at desc);

alter table public.claim_admin_events enable row level security;
alter table public.confirmation_reminder_events enable row level security;

drop policy if exists "Super admin reads all claims" on public.claim_records;
create policy "Super admin reads all claims" on public.claim_records
for select to authenticated using (public.is_super_admin());

drop policy if exists "Super admin reads all confirmations" on public.confirmation_requests;
create policy "Super admin reads all confirmations" on public.confirmation_requests
for select to authenticated using (public.is_super_admin());

drop policy if exists "Super admin reads claim admin events" on public.claim_admin_events;
create policy "Super admin reads claim admin events" on public.claim_admin_events
for select to authenticated using (public.is_super_admin());

drop policy if exists "Super admin reads confirmation reminders" on public.confirmation_reminder_events;
create policy "Super admin reads confirmation reminders" on public.confirmation_reminder_events
for select to authenticated using (public.is_super_admin());

-- Allows Super Admin to create short-lived signed links to claim PDFs.
drop policy if exists "Super admin reads claim PDFs" on storage.objects;
create policy "Super admin reads claim PDFs" on storage.objects
for select to authenticated
using (bucket_id = 'claim-pdfs' and public.is_super_admin());

-- A returned claim may be corrected by its owning IFAR.
-- These policies coexist with the project's existing owner policies.
drop policy if exists "IFAR updates own returned claim" on public.claim_records;
create policy "IFAR updates own returned claim" on public.claim_records
for update to authenticated
using (adviser_id = auth.uid() and status = 'RETURNED')
with check (adviser_id = auth.uid() and status in ('RETURNED', 'READY'));

create or replace function public.admin_claim_records()
returns table (
  id uuid, adviser_id uuid, claim_ref text, applicant_name text,
  account_holder_name text, account_number text, claim_date date,
  total_amount numeric, status text, pdf_path text, created_at timestamptz,
  received_at timestamptz, returned_at timestamptz, return_reason text,
  adviser_email text, adviser_name text
)
language sql stable security definer set search_path = public, auth
as $$
  select c.id, c.adviser_id, c.claim_ref, c.applicant_name,
    c.account_holder_name, c.account_number, c.claim_date, c.total_amount,
    c.status, c.pdf_path, c.created_at, c.received_at, c.returned_at,
    c.return_reason, u.email::text,
    coalesce(u.raw_user_meta_data ->> 'full_name', split_part(u.email, '@', 1))
  from public.claim_records c
  join auth.users u on u.id = c.adviser_id
  where public.is_super_admin()
  order by c.created_at desc;
$$;

create or replace function public.admin_confirmation_records()
returns table (
  id uuid, adviser_id uuid, reference_no text, participant_name text,
  participant_email text, certificate_no text, adviser_name text,
  adviser_email text, status text, created_at timestamptz,
  client_signed_at timestamptz, adviser_signed_at timestamptz,
  last_reminded_at timestamptz, reminder_count bigint
)
language sql stable security definer set search_path = public, auth
as $$
  select c.id, c.adviser_id, c.reference_no, c.participant_name,
    c.participant_email, c.certificate_no, c.adviser_name, u.email::text,
    c.status, c.created_at, c.client_signed_at, c.adviser_signed_at,
    max(r.occurred_at), count(r.id)
  from public.confirmation_requests c
  join auth.users u on u.id = c.adviser_id
  left join public.confirmation_reminder_events r on r.confirmation_id = c.id
  where public.is_super_admin()
  group by c.id, u.email
  order by c.created_at desc;
$$;

revoke all on function public.admin_claim_records() from public;
revoke all on function public.admin_confirmation_records() from public;
grant execute on function public.admin_claim_records() to authenticated;
grant execute on function public.admin_confirmation_records() to authenticated;
